/** Feature flags. A school's effective features = plan.features ∪ tenant.featureOverrides. */
export const FEATURES = {
  ACADEMICS: 'ACADEMICS',
  ATTENDANCE: 'ATTENDANCE',
  OFFLINE_SYNC: 'OFFLINE_SYNC',
  FEES: 'FEES',
  RESULTS: 'RESULTS',
  TIMETABLE: 'TIMETABLE',
  CANTEEN: 'CANTEEN',
  PARENT_PORTAL: 'PARENT_PORTAL',
  WEBSITE: 'WEBSITE',
  CUSTOM_DOMAIN: 'CUSTOM_DOMAIN',
  COMMUNICATIONS: 'COMMUNICATIONS',
  INVENTORY: 'INVENTORY',
  ANALYTICS: 'ANALYTICS',
  API: 'API',
  DISCIPLINE: 'DISCIPLINE',
  EVENTS: 'EVENTS',
  ASSIGNMENTS: 'ASSIGNMENTS',
  LIBRARY: 'LIBRARY',
  TRANSPORT: 'TRANSPORT',
  HEALTH: 'HEALTH',
  MESSAGING: 'MESSAGING',
  HR: 'HR',
} as const;

export type Feature = keyof typeof FEATURES;
export const ALL_FEATURES = Object.keys(FEATURES);
/** Always available regardless of plan. */
export const CORE_FEATURES = [FEATURES.ACADEMICS, FEATURES.ATTENDANCE];

export const DEFAULT_PLANS = [
  {
    code: 'STARTER',
    name: 'Starter',
    description: 'Core academics, attendance, fees and expense tracking for small schools',
    priceMonthly: 150,
    priceYearly: 1500,
    studentLimit: 200,
    trialDays: 90,
    sortOrder: 1,
    features: ['ACADEMICS', 'ATTENDANCE', 'OFFLINE_SYNC', 'FEES', 'RESULTS', 'EVENTS'],
  },
  {
    code: 'PROFESSIONAL',
    name: 'Professional',
    description:
      'Everything a growing school needs, including canteen and feeding billing, a parent portal and website',
    priceMonthly: 400,
    priceYearly: 4000,
    studentLimit: 1000,
    trialDays: 90,
    sortOrder: 2,
    features: [
      'ACADEMICS',
      'ATTENDANCE',
      'OFFLINE_SYNC',
      'FEES',
      'RESULTS',
      'TIMETABLE',
      'CANTEEN',
      'PARENT_PORTAL',
      'WEBSITE',
      'COMMUNICATIONS',
      'INVENTORY',
      'ANALYTICS',
      'DISCIPLINE',
      'EVENTS',
      'ASSIGNMENTS',
      'MESSAGING',
      'HEALTH',
      'LIBRARY',
    ],
  },
  {
    code: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'Large schools and groups: custom domain, API access and advanced analytics',
    priceMonthly: 700,
    priceYearly: 7000,
    studentLimit: 100000,
    trialDays: 90,
    sortOrder: 3,
    features: ALL_FEATURES,
  },
];
